tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'caskroom/drivers'
tap 'universal-ctags/universal-ctags'
tap 'mkchoi212/fac'
tap 'heroku/brew'

# Cool System Stuff
cask 'aerial' # Screensaver videos

# Fonts
cask 'font-source-code-pro'

# Security
cask 'authy'
cask 'nordvpn'
brew 'pinentry-mac'
brew 'gnupg'
cask 'keybase'
cask '1password'

# Terminal
brew 'ack'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'coreutils'
brew 'dos2unix'
brew 'fzy'
brew 'jq'
brew 'nmap'
brew 'readline'
brew 'rbenv'
brew 'ruby-build'
brew 'rbenv-default-gems'
brew 'the_silver_searcher'
brew 'tldr'
brew 'unar'
brew 'vim'

# Development
cask 'atom'
cask 'ccmenu'
cask 'docker'
brew 'fac'
brew 'git'
cask 'google-cloud-sdk'
brew 'heroku'
brew 'hub'
brew 'nvm'
cask 'postman'
cask 'p4merge'
brew 'python'
brew 'tig'
brew 'tmate'
brew 'tmux'
brew 'universal-ctags', args: ['HEAD']

cask 'google-chrome'
cask 'firefox'

# Text Editing
mas 'keynote', id: 409183694
mas 'numbers', id: 409203825
mas 'pages', id: 409201541

# Utility Apps
cask '1password'
cask 'disk-inventory-x'
cask 'dropbox'
brew 'fzf'
cask 'gimp'
cask 'google-backup-and-sync'
cask 'google-drive'
cask 'slack'
cask 'spectrum'
cask 'spotify'
brew 'task'
brew 'tree'
cask 'the-unarchiver'
